config/routes.rb
Rails.application.routes.draw do
  get 'stores/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :dashboard, only: [:show] do
    member do
      get 'profile'
      get 'orders'
      get 'wishlist'
      get 'listings'
    end
  end

  post "/add_item_wishlist/:id", to: "products#add_to_wishlist", as: "add_to_wishlist"
  delete "/delete_from_wishlist/:id", to: "products#delete_from_wishlist", as: "delete_from_wishlist"
  delete "/delete_in_wishlist/:id", to: "products#destroy", as: "delete_in_wishlist"
  # delete "/dashboard/wishlist/:id", to: "products#destroy", as: "delete_in_wishlist"

  resources :stores, only: [:show], as: 'store' do
    member do
      get 'chat', to: 'chatrooms#create'
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :products do
    resources :reviews, only: [ :new, :create ]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :reviews, except: [ :new, :create]

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end

  resource :cart
  resources :cart_items, only: [:destroy]
  post "/add_item_cart/:id", to: "carts#add_to_cart", as: "add_to_cart"
  patch "/update_amount/:id", to: "carts#update_amount", as: "update_amount"
  # delete "/delete_cart_item/:id", to: "carts#destroy", as: "delete_cart_item"

  post "/increase_amount/:id", to: "carts#increase_amount", as: "increase_amount"
  post "/decrease_amount/:id", to: "carts#decrease_amount", as: "decrease_amount"


end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def show
    @store = User.find(params[:id])
    @reviews = reviews
    @average_rating = average_reviews
  end

  private

  def reviews
    @store.products.each do |product|
      product.reviews
    end
  end

  def average_reviews
    sum = 0
    @store.products.each do |product|
      product.reviews.each do |review|
        sum += review.stars
      end
    end

    review_sum = 0
    @store.products.each do |product|
      review_sum += product.reviews.count
    end
    sum
    @average_rating = sum/review_sum.to_f
    @average_rating.round(1)
  end
end

app/views/stores/show.html.erb
<div class="body">
<!-- <div class="top d-flex space-between">
    <div class="banner">
      <h1 class="mt-5 mb-4">
        <span id="banner-typed-text"></span>
      </h1>
      <br>
    </div>
  -->

  <div class="container seller-container">
    <div class="seller-info d-flex justify-content-center mt-5">
      <% if @store.avatar.attached? %>
      <div class="seller-picture mr-4 "> <%= cl_image_tag @store.avatar.key, alt: "profilepic", class: "seller-picture" %></div>
      <% else %>
      <%= image_tag "umbrellashop.jpg", width:300,  height: 200, alt: "alttext" %>
      <% end %>
      <div class="top-level-info">
        <div><h3><%= @store.full_name  %></h3></div>
        <p><strong>Based in: </strong><%= @store.full_address  %></p>
        <div class="quick-info d-flex">
          <div class="details">
            <p class="detail-name">Products</p>
            <p class="detail-nr"><%= @store.products.count %></p>
          </div>
          <div class="details">
            <p class="detail-name">Reviews</p>
            <p class="detail-nr"><%= @reviews.count %></p>
          </div>
          <div class="details">
            <p class="detail-name">Average rating</p>
            <p class="detail-nr"> <%= @average_rating %></p>
          </div>
        </div>
        <div class="d-flex">
          <div class="chat-button mr-4"><%= link_to "Chat with #{@store.first_name}", chat_store_path(@store) %></div>
          <!-- <div class="follow-button"><%#= link_to "Follow #{@store.first_name}", chatrooms_store_path(@store) %></div> -->
        </div>
      </div>
    </div>
    <div class="seller-detailed-info">
      <h3 class="mt-5">Who we are</h3>
      <p>We offer high quality umbrellas that fit to every outfit. We are always happy when our customers are happy. Just like our customers, we don't want the low prices of our products to come at a high price elsewhere. We do not own factories or workshops of our own, but our suppliers are our partners, and each and every one of them has pledged to follow the specifications of our code of conduct.
</p>
      <h3 class="mt-5">Our contribution to the environment</h3>
      <p class="mb-5">To us, assuming corporate responsibility includes a respectful approach to resources and the natural world. Our collections change rapidly. That makes it all the more important to ensure that everything we do as a company is geared toward long-term sustainability, including – and especially – when it comes to the environment. We have already banned PVC from all of our products and packaging. For our products we have committed to reduce CO2emissions. And whatever "leftovers" there may be are neutralized through reforestation.</p>

      <!--<p><strong>Favorite product: </strong> <%= link_to @store.products.first.name, product_path(@store.products.first) %></p> -->
      <% @store.products.each do |product| %>
      <%= render partial: "products/card", locals: { product: product } %>
      <% end %>
    </div>
</div>

<!--
<div class="reviews m-5">
            <div class="d-flex">
              <h3 class="mr-5">Reviews</h3>
              <div class="add-review justify-content-center align-items-center"></div>
            </div>
            <ul class="list-group">
<% @store.products.each do |product|%>
              <div class="review mt-2 border-top">
                <div class="stars d-flex pt-2">
                  <div class="stars-full d-flex">
                    <% product.reviews.each do |review|%>
                    <% review.stars.times do %>
                    <i class="fas fa-star"></i>
                  </div>

                  <div class="stars-empty d-flex">
                    <% (5 - review.stars).times do %>
                    <i class="far fa-star"></i>
                    <% end %>
                  </div>
                </div>
                <div class="review-description pt-2">
                  <%= review.description%>
                  <% end %>
                      <% end %>
                    <% end %>
                </div>
              </div>
            </ul>
          </div>



        --></div>