config/routes.rb
Rails.application.routes.draw do
  get 'stores/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :dashboard, only: [:show] do
    member do
      get 'profile'
      get 'orders'
      get 'wishlist'
      get 'listings'
    end
  end

  post "/add_item_wishlist/:id", to: "products#add_to_wishlist", as: "add_to_wishlist"
  delete "/delete_from_wishlist/:id", to: "products#delete_from_wishlist", as: "delete_from_wishlist"
  delete "/delete_in_wishlist/:id", to: "products#destroy", as: "delete_in_wishlist"
  # delete "/dashboard/wishlist/:id", to: "products#destroy", as: "delete_in_wishlist"

  resources :stores, only: [:show], as: 'store' do
    member do
      get 'chat', to: 'chatrooms#create'
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :products do
    resources :reviews, only: [ :new, :create ]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :reviews, except: [ :new, :create]

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end

  resource :cart
  resources :cart_items, only: [:destroy]
  post "/add_item_cart/:id", to: "carts#add_to_cart", as: "add_to_cart"
  patch "/update_amount/:id", to: "carts#update_amount", as: "update_amount"
  # delete "/delete_cart_item/:id", to: "carts#destroy", as: "delete_cart_item"

  post "/increase_amount/:id", to: "carts#increase_amount", as: "increase_amount"
  post "/decrease_amount/:id", to: "carts#decrease_amount", as: "decrease_amount"


end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  monetize :price_cents

  after_touch :calculate_total_price

  def calculate_total_price
    self.cart_items.reload
    self.price = self.cart_items.sum(&:price)
    self.save
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :find_create_cart

  def show
    @cart_items = @cart.cart_items.order(id: :desc)
  end

  def add_to_cart
    chosen_product = Product.find(params[:id])
    @cart = Cart.new if @cart.status == 'ordered'
    @cart_item = CartItem.find_or_create_by(product: chosen_product, cart: @cart)
    @cart_item.amount += 1
    @cart_item.save
    @cart.calculate_total_price
    redirect_back(fallback_location: root_url, notice: "Product has been added to cart")
  end

  def edit
    @cart_item = CartItem.find(params[:id])
  end

  def update_amount
    # TODO
    @cart_item = CartItem.find(params[:id])
    @cart_item.update!(cart_item_params)
    redirect_to cart_path
  end

  def increase_amount
    @cart_item = CartItem.find(params[:id])
    @cart_item.amount += 1
    @cart_item.save
    redirect_to cart_path(anchor: "cart-item-#{@cart_item.id}")
  end

  def decrease_amount
    @cart_item = CartItem.find(params[:id])
    @cart_item.amount -= 1
    if @cart_item.amount >= 1
      @cart_item.save
    else
      @cart_item.destroy
    end
    redirect_to cart_path(anchor: "cart-item-#{@cart_item.id}")
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to products_path
  end

  private

  def cart_params
    params.require(:cart).permit(:total_price, :order_number, :status)
  end

  def cart_item_params
    params.require(:cart_item).permit(:amount)
  end

  def find_create_cart
    @cart = Cart.find_or_create_by(user: current_user, status: "pending")
  end
end

app/views/carts/show.html.erb
<div class="container ml-0 pl-0">
  <div class="row mt-5 ml-0 pl-0">
      <div class="col-2 ml-0 pl-0">
      <%= render "dashboards/sidebar" %>
    </div>
    <div class="col-10">
      <div class="first-line mb-5 border-bottom">
        <div class="title">
          <h3> <%= current_user.first_name %>'s cart</h3>
        </div>

        <!-- <div class="delete-cart">
          <%#= link_to cart_path, method: :delete, data: { confirm: "Are you sure you want to delete your cart?" } do %>
          <i class="fas fa-trash"></i>
          <%# end %>
        </div> -->

      <p>You have <strong><%= @cart_items.count %> product</strong> in your cart. </p>
      </div>
      <div class="cart-body">
        <% @cart_items.each do |cart_item|%>
        <div class="cart-item border-bottom" >
          <div class="d-flex align-items-center text-md-center row" id="cart-item-<%=cart_item.id%>">
            <div class="cart-item-img col-2">
              <!-- TODO: link to single product has to be fixed -->
              <%= link_to products_path(@product) do %>
              <%= cl_image_tag cart_item.product.photos.first.key if cart_item.product.photos.attached?%>
              <% end %>
            </div>
            <div class="cart-item-title text-left col-2">
              <%= cart_item.product.name %>
            </div>
            <div class="cart-item-info d-flex align-items-center col-8">
              <div class="cart-item-single-price d-flex col-1">
                € <%= cart_item.product.price.round%>
              </div>
              <div class="cart-item-delivery-option d-flex align-items-center col-2">
                <%#= cart_item.product.delivery_options.sample.name%>
                <!-- Fake for presentation -->
                Instant Bike Delivery
              </div>
              <div class="cart-item-complete-amount d-flex align-items-center col-3">
               <div class="cart-item-amount-down border">
                <%=  link_to decrease_amount_path(cart_item), method: :post, remote: true do %>
                <%= image_tag "icons/arrow_down.svg", alt: "arrowdown", class:"arrow-icon" %>
                <% end %>
              </div>
              <div class="cart-item-amount border">
                <%= cart_item.amount %>
              </div>
              <div class="cart-item-amount-up border">
                <%=  link_to increase_amount_path(cart_item), method: :post, remote: true do %>
                <%= image_tag "icons/arrow_up.svg", alt: "arrowup", class:"arrow-icon" %>
                <% end %>
              </div>
            </div>
            <div class="cart-item-price d-flex align-items-center col-1">
              € <%= cart_item.price.round%>
            </div>
            <div class="cart-item-delete d-flex align-items-center col-1" id="trash">
              <%= link_to cart_item_path(cart_item), method: :delete, data: { confirm: "Are you sure you want to delete this product?" } do %>
              <i class="fas fa-times"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="bottom-line d-flex justify-content-between align-items-center">
      <div class="">
        <h6><strong>Total order price: </strong></h6>
      </div>
      <div class="bottom-checkout-right d-flex align-items-center">
        <h6 class="total-price-db"><strong> <%= humanized_money_with_symbol(@cart.price) %></h6></strong>
        <div class="order-btn ml-5">
          <%= form_tag orders_path do %>
          <%= hidden_field_tag 'cart', @cart.id %>
          <%= submit_tag 'Purchase', class: 'btn btn-dark order-btn' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  </div>
</div>