config/routes.rb
Rails.application.routes.draw do
  get 'stores/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :dashboard, only: [:show] do
    member do
      get 'profile'
      get 'orders'
      get 'wishlist'
      get 'listings'
    end
  end

  post "/add_item_wishlist/:id", to: "products#add_to_wishlist", as: "add_to_wishlist"
  delete "/delete_from_wishlist/:id", to: "products#delete_from_wishlist", as: "delete_from_wishlist"
  delete "/delete_in_wishlist/:id", to: "products#destroy", as: "delete_in_wishlist"
  # delete "/dashboard/wishlist/:id", to: "products#destroy", as: "delete_in_wishlist"

  resources :stores, only: [:show], as: 'store' do
    member do
      get 'chat', to: 'chatrooms#create'
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :products do
    resources :reviews, only: [ :new, :create ]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :reviews, except: [ :new, :create]

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end

  resource :cart
  resources :cart_items, only: [:destroy]
  post "/add_item_cart/:id", to: "carts#add_to_cart", as: "add_to_cart"
  patch "/update_amount/:id", to: "carts#update_amount", as: "update_amount"
  # delete "/delete_cart_item/:id", to: "carts#destroy", as: "delete_cart_item"

  post "/increase_amount/:id", to: "carts#increase_amount", as: "increase_amount"
  post "/decrease_amount/:id", to: "carts#decrease_amount", as: "decrease_amount"


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @products = Product.all
    # @product = Product.find(params[:id])
    @cart = Cart.find_or_create_by(user: current_user, status: "pending")
  end

  def profile
  end

  def orders
    @orders = Order.where(user: current_user)
  end
end

app/views/dashboards/_sidebar.html.erb
<nav id="sidebar">
  <div class="background-img text-center py-4">
    <% if current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key, width: 400, height: 400, crop: :crop, radius: :max, gravity: :face, class:"avatar sidebar", id:"navbarDropdown", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }%>
          <% else %>
          <a href="" class="nav-link dropdown-toggle icon" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name[0]%><%=  current_user.last_name[0] %></a>
          <% end %>
    <h5 class="sidebar-name"><a href="/dashboard/profile"><%= current_user.full_name %></h5></a>
  </div>
  <ul class="list-unstyled components mb-5">
    <li>
      <a href="/dashboard/profile"><i class="icon-sidebar fas fa-house-user mr-3"></i></i>Profile</a>
    </li>
    <li>
      <a href="/dashboard/wishlist"><i class="icon-sidebar fas fa-heart mr-3"></i>Wishlist</a>
    </li>
    <li>
      <a href="/cart"><i class="icon-sidebar fas fa-shopping-cart mr-3"></i>Cart</a>
    </li>
    <% #if current_user.seller_approved == true %>
    <li>
      <a href="/chatrooms"><i class="icon-sidebar fas fa-comment mr-3"></i>Messages</a>
    </li>
    <li>
      <a href="/dashboard/listings"><i class="icon-sidebar fas fa-folder-open mr-3"></i>Listings</a>
    </li>
    <% #end %>
</ul>
</nav>




<!-- <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#" role="tab" aria-controls="v-pills-home" aria-selected="true">Cart</a>
  <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="/dashboard/profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Profile</a>
  <%#= link_to "Profile", profile_dashboard_path, class:"nav-link", id:"v-pills-profile-tab", role:"tab" %>
  <%#= link_to "Wishlist", wishlist_dashboard_path, class:"nav-link", id:"v-pills-profile-tab", role:"tab" %>
  <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</a>
  <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Settings</a>
  <%# if current_user.seller_approved == true %>
  <a class="nav-link" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">listings</a>
  <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</a>
  <%# end %>
</div>
-->

app/views/dashboards/listings.html.erb
<h1>Your sold products</h1>

<% current_user.cart_items_as_owner.each do |cart_item|%>
<%= cart_item.product.name %>
<%= cart_item.cart.status %>
<% end %>



<% current_user.products.each do |product| %>
<%= product.name %>
<% end %>

app/views/dashboards/orders.html.erb
<div class="container">
  <% @orders.each do |order| %>
    <h1>Order: <%= link_to order.id, order_path(order) %><span class="badge badge-secondary"><%= order.state %></span></h1>
  <% end %>
</div>

app/views/dashboards/profile.html.erb
<div class="container ml-0 pl-0">
  <div class="row mt-5 ml-0 pl-0">
      <div class="col-2 ml-0 pl-0">
        <%= render "sidebar" %>
      </div>







    <div class="center-content">
      <h3><strong>Change profile</strong></h3>
      <% if current_user.avatar.attached? %>
      <%= cl_image_tag current_user.avatar.key, width: 200  %>
      <% end %>
      <div class="simple-border-card">
        <div class="welcome-user-card-info">
          <h5><strong>This is you</strong><% if current_user.seller_approved == true %><div class="badge alert-succes" role="alert">You are a seller</div><% end %></h5>
          <p class="user-info-card-dashboard"><%= current_user.first_name %> <%= current_user.last_name %></p>
          <p class="user-info-card-dashboard"><%= current_user.street_name %> <%= current_user.street_number %></p>
          <p class="user-info-card-dashboard"><%= current_user.postal_code %> <%= current_user.city %></p>
          <p><%= current_user.email %></p>
          <p class="info-card-dashboard">New address? Other name? You can adjust that and more here.</p>
          <%= link_to "Change account details", edit_user_registration_path  %>
        </div>
        <div class="card-photo-dashboard">
          <%= image_tag "account.svg", alt: "alttext" %>
        </div>
      </div>
      <div class="simple-border-card">
        <div class="welcome-user-card-info">
          <h5><strong>Apply to be a seller</strong></h5>
          <ul>
            <li><p class="user-info-card-dashboard">Item 1</p></li>
            <li><p class="user-info-card-dashboard">Item 2</p></li>
            <li><p class="user-info-card-dashboard">Item 3</p></li>
          </ul>
          <p class="info-card-dashboard">Would you like to sell your products on our platform? Off course you would like that, don't wait and sign up now</p>
          <%= link_to "Sign up as seller", edit_user_registration_path, class:"btn btn-primary" %>
        </div>
        <div class="card-photo-dashboard">
          <%= image_tag "business.svg", alt: "alttext" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="container ml-0 pl-0">
  <div class="row mt-5 ml-0 pl-0">
      <div class="col-2 ml-0 pl-0">
        <%= render "sidebar" %>
      </div>

    <div class="col-10">
    <div class="center-content">
      <h3><strong>Welcome to your account</strong></h3>
      <div class="welcome-user-card">
        <div class="welcome-user-card-info">
          <h5>Hello <strong><%= current_user.first_name %>,<strong></h5>
          <p>here you will find all your relevant information</p>
        </div>
        <div class="welcome-user-card-photo">
          <img src="undraw_female_avatar_w3jk.svg" alt="">
        </div>
      </div>

       <% @cart.cart_items.each do |cart_item|%>
       <div class="card-product m-2">
        <%= cl_image_tag cart_item.product.photos.first.key if cart_item.product.photos.attached? %>
        <div class="card-product-infos">
          <h2><%= link_to cart_item.product.name, products_path(@product) %></h2>
          <p> <%= cart_item.amount%> x EUR <%= cart_item.product.price %></p>
        </div>
      </div>
      <% end %>

      <div class="totalprice">
        <%= humanized_money_with_symbol(@cart.price) %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/dashboards/wishlist.html.erb
<div class="container ml-0 pl-0">
  <div class="row mt-5 ml-0 pl-0">
      <div class="col-2 ml-0 pl-0">
      <%= render "sidebar" %>
    </div>

    <div class="col-10">
      <div class="wishlist-header mb-5 border-bottom">
        <h3> <%= current_user.first_name %>'s wishlist</h3>
        <p>You have <strong><%= current_user.wishlist_products.count %> product</strong> in your wishlist. </p></div>

        <div class="wishlist-body">
          <% current_user.wishlist_products.each do |product| %>
          <div class="wishlist-item d-flex align-items-center text-left text-md-center" >
              <div class="wishlist-item-img col-2">
                <%= link_to product_path(product), class: "card-link" do %>
                <%= cl_image_tag product.photos.first.key%>
              <% end %>
              </div>
              <div class="cart-item-title text-left col-2">
                <%= product.name %>
              </div>
              <div class="wishlist-item-info d-flex align-items-center col-8">
                <div class="wishlist-item-single-price d-flex col-1">
                  € <%= product.price.round%>
                </div>
                <div class="wishlist-item-delivery-option d-flex align-items-center col-2">
                <%= product.delivery_options.sample.name %>
                </div>
                <div class="add-to-cart-button d-flex align-items-center col-3">
                  <%= link_to add_to_cart_path(product), method: :post do %>
                  <i class="fas fa-cart-plus"></i>
                  <% end %>
                </div>

                <div class="wishlist-item-delete d-flex align-items-center col-2" id="trash">
                  <%= link_to delete_in_wishlist_path(product), method: :delete do %>
                  <i class="fas fa-times"></i>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>