config/routes.rb
Rails.application.routes.draw do
  get 'stores/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :dashboard, only: [:show] do
    member do
      get 'profile'
      get 'orders'
      get 'wishlist'
      get 'listings'
    end
  end

  post "/add_item_wishlist/:id", to: "products#add_to_wishlist", as: "add_to_wishlist"
  delete "/delete_from_wishlist/:id", to: "products#delete_from_wishlist", as: "delete_from_wishlist"
  delete "/delete_in_wishlist/:id", to: "products#destroy", as: "delete_in_wishlist"
  # delete "/dashboard/wishlist/:id", to: "products#destroy", as: "delete_in_wishlist"

  resources :stores, only: [:show], as: 'store' do
    member do
      get 'chat', to: 'chatrooms#create'
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :products do
    resources :reviews, only: [ :new, :create ]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :reviews, except: [ :new, :create]

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end

  resource :cart
  resources :cart_items, only: [:destroy]
  post "/add_item_cart/:id", to: "carts#add_to_cart", as: "add_to_cart"
  patch "/update_amount/:id", to: "carts#update_amount", as: "update_amount"
  # delete "/delete_cart_item/:id", to: "carts#destroy", as: "delete_cart_item"

  post "/increase_amount/:id", to: "carts#increase_amount", as: "increase_amount"
  post "/decrease_amount/:id", to: "carts#decrease_amount", as: "decrease_amount"


end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :user
  has_many :cart_items, dependent: :destroy
  #has_many :delivery_options
  # has_many :carts, through: :cart_item
  has_many_attached :photos
  has_many :reviews, dependent: :destroy
  belongs_to :category
  belongs_to :subcategory

  # has_and_belongs_to_many

  has_many :delivery_options, dependent: :destroy
  accepts_nested_attributes_for :delivery_options

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  # validate :subcategory_part_of_category

 include PgSearch::Model
  pg_search_scope :global_search,
    against: [:name, :description],
    associated_against: {
      user: [:first_name, :last_name]
    },
    using: {
      tsearch: { prefix: true }
    }

    def average_reviews
    sum = 0
      self.reviews.each do |review|
        sum += review.stars
      end
    review_sum = self.reviews.count
    sum
    @average_rating = sum/review_sum.to_f
    @average_rating.round(1)
  end

    # def subcategory_part_of_category
    #   errors.add(:category, "subcategory not part of category") unless subcategory.category == category
    # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # TODO: somehow include subcategories in here
    @products = Product.all
    if params[:subcategory].present?
      @products = @products.joins(:subcategory).where(subcategories: { name: params[:subcategory] })
    elsif params[:category].present?
      @products = @products.joins(:category).where(categories: { name: params[:category] })
    end

    if params[:subcategories].present?
      @products = Product.joins(:subcategory).where(subcategories: { id: params[:subcategories] })
    end

    if params[:delivery_option].present?
      product_ids = DeliveryOption.where(name: params[:delivery_option]).pluck(:product_id)
      @products = @products.where(id: product_ids)
    end

    if params[:lon].present? && params[:lat].present?
      @user_ids = User.near([params[:lat], params[:lon]], 3).map(&:id)
      @products = @products.where(user_id: @user_ids)
    end

    if params[:query].present?
      @products = @products.global_search(params[:query])
    end

    if params[:location].present?
      @user_ids = User.near(params[:location], 10).map(&:id)
      @products = @products.where(user_id: @user_ids)
    end

    if params[:min_price].present? || params[:max_price].present?
      @products = @products.where("price >= ? AND price <= ?", params[:min_price].to_f, params[:max_price].to_f)
    end
    map

    @average_reviews = average_reviews
  end

  def show
    @product = Product.find(params[:id])
    @cart = Cart.new
    @user = @product.user
    @user.geocode
    @marker =
      [{
      lat: @user.latitude,
      lng: @user.longitude,
      id: @user.id,
      infoWindow: render_to_string(partial: "info_window", locals: { user: @user }),
      image_url: helpers.asset_url('shop_marker.png')
    }]
    if user_signed_in?
      @product_in_wishlist = current_user.wishlist_products.any? { |product| product == @product }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product = Product.update(product_params)
    redirect_to product_path(@product)
    # how to add possibility to update pictures?
  end

  def new
    @product = Product.new
    @product.delivery_options.build
  end

  # create is not working yet

  def create
    @product = Product.new(product_params_filtered)
    @product.user = current_user
    @product.category = Category.find(params[:product][:category_id])
    @product.subcategory = Subcategory.find(params[:product][:subcategory_id])
    if @product.save!
      redirect_to product_path(@product)
    else
      render "new"
    end
  end

  def add_to_wishlist
    chosen_product = Product.find(params[:id])
    @user = current_user
    if current_user.wishlist_products.any? { |product| product == chosen_product }
      redirect_to product_path(chosen_product), notice: "Product already in wishlist"
    else
      current_user.wishlist_products << chosen_product
      redirect_to product_path(chosen_product), notice: "Product has been added to wishlist"
    end
  end

  def delete_from_wishlist
    @product = Product.find(params[:id])
    current_user.wishlist_products.destroy(@product)
    redirect_to product_path(@product), notice: "Product has been deleted from wishlist"
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to wishlist_dashboard_path
  end

  private

  def map
    @user = User.seller
    @markers = @user.geocoded.map do |user| {
      lat: user.latitude,
      lng: user.longitude,
      id: user.id,
      infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
      image_url: helpers.asset_url('shop_marker.png')
    }
    end
  end


  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id, photos: [], delivery_options_attributes: [:name, :price])
  end

  def product_params_filtered
    new_product_params = product_params
    new_product_params[:delivery_options_attributes].reject!{ |key, delivery_options|
      !delivery_options[:name].in?(params[:offered_delivery_options].keys)
    }
    new_product_params
  end

  def average_reviews
    sum = 0
    @products.each do |product|
      product.reviews.each do |review|
        sum += review.stars
      end
    end
    review_sum = 0
    @products.each do |product|
      review_sum += product.reviews.count
    end
    sum
    @average_rating = sum/review_sum.to_f
    @average_rating.round(1)
  end
end

app/views/products/_card.html.erb
<div class="card-product m-2">
  <%= link_to product_path(product) do %>
  <%= cl_image_tag product.photos.first.key if product.photos.attached? %>
  <div class="card-product-infos">
    <h2><%=product.name %></h2>
    <p> EUR <%= product.price %></p>
    <hr>
    <p> Sold by: <%= link_to product.user.full_name, store_path(product.user) %></p>
    <% product.average_reviews %>


    <% if product.reviews.count > 0  %>
    <div class="stars d-flex align-items-center pt-2">
      <% 5.times do |num| %>
      <i class="fa<%=product.average_reviews.round < num + 1 ? 'r' : 's' %> fa-star"></i>
      <% end %>
      <div>
        <p class="ml-2">(<%= product.average_reviews %>)</p>
      </div>
    </div>
    <% else %>
    <p>No reviews</p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/products/_info_window.html.erb
<!-- <div class="seller-marker d-flex flex-column align-items-left"> -->

<div id="markerCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#markerCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#markerCarousel" data-slide-to="1"></li>
    <li data-target="#markerCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <% if user.products.first.photos.attached? %>
         <%= cl_image_tag user.products.first.photos.first.key, class: "window-pic" %>
         <% else %>
         hello
      <% end %>

      <div class="carousel-caption d-none d-md-block">
        <h5> <%= link_to user.products.first.name, product_path(user.products.first), class: "product-marker-name" %></h5>
      </div>
    </div>
    <% user.products.each do |product| %>
    <div class="carousel-item">
      <% if product.photos.attached? %>
        <%= cl_image_tag product.photos.first.key, class: "window-pic" %>
      <% else %>
         hello
      <% end %>
      <div class="carousel-caption d-none d-md-block">
        <h5> <%= link_to product.name, product_path(product), class: "product-marker-name" %></h5>
      </div>
    </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#markerCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#markerCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<h2 class="mb-1"><%= user.full_name %></h2>
<p class="marker-address mb-1"><i class="fas fa-map-marker-alt"></i> <%= user.full_address %></p>
<p class="marker-reviews mt-1"><i class="fas fa-star"></i><%= user.average_reviews %> (<%= user.review_sum %>)</p>
<!-- <p class="marker-products"> <%#= link_to "See all #{user.products.count} products"%> </p> -->
<!-- </div> -->

<div class="store-link">
  <%= link_to "See all #{user.products.count} products of #{user.first_name}", store_path(user) %>
</div>

app/views/products/edit.html.erb
<%= render "shared/new_product_form" %>

app/views/products/index.html.erb
<!-- <div class="container"> -->
  <div class="big-container">
    <div class="row ml-2">
      <div class="col-6">
        <%= form_tag products_path, method: :get do %>
        <%= hidden_field_tag :query, params[:query] %>
        <%= hidden_field_tag :location, params[:location] %>
        <%= hidden_field_tag :category, params[:category] %>
        <%= hidden_field_tag :delivery_option, params[:delivery_option] %>
        <div class="filters d-flex justify-content-between">
          <div class="filters d-flex ">
            <div class="price-filter">
              <h6 class="mb-0">Price</h6>
            <!-- <input type="button" name="answer" value="Filter for price" onclick="showFilter()" />
              <div id="show-price-filter" style="display:none;"> -->
                <div class="price-filter mt-1 d-flex">
                  <div class="input-group min-price price mb-3">
                    <div class="input-group-prepend price">
                      <span class="input-group-text euro-sign">€</span>
                    </div>
                    <input type="number" min=0 name="min_price" id="min_price" class="form-control" placeholder="Min">
                  </div>
                  <div class="input-group max-price mb-3">
                    <input type="number" min=0 name="max_price" id="max_price" class="form-control" placeholder="Max">
                  </div>
                  <div>
                  </div>
                </div>
                <!-- </div> -->
              </div>
              <div class="del-option">
                <h6 class="mb-0">Delivery Options</h6>
                <%= select_tag "delivery_option", options_for_select(["Pick-up", "Postal Delivery", "Instant Bike Delivery"], params[:delivery_option]), class: "delivery-otions-filter" %>
              </div>
            </div>
      <!--     <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Delivery Options
           </button>
           <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Pick-up</a>
            <a class="dropdown-item" href="#">Postal Delivery</a>
            <a class="dropdown-item" href="#">Instant Bike Delivery</a>
          </div>
        </div> -->
        <div class="category-filter">
          <% if params[:category].present? %>
          <h6 class="mb-0">Subcategories</h6>
          <% category = Category.find_by_name(params[:category]) %>
          <% category.subcategories.each_with_index do |subcategory, index| %>
          <div class="form-check form-check-inline">
            <div class= "align-items-center">
              <%= check_box_tag "subcategories[]", subcategory.id, nil, id: "subcategories_#{subcategory.id}", class: "checkbox-category" %>
              <%= label_tag "subcategories_#{subcategory.id}", subcategory.name %>
            </div>
          </div>
          <% end %>
          <% end %>
          <%= button_tag(type: "submit", class: "btn btn-default") do %>
          <i class="fas fa-search"></i>
          <% end %>
        </div>
      </div>
      <% end %>
      <div class="product-cards mt-4">
        <h1 class="mb-2"><strong>Our products</strong></h1>
        <div class="cards">
        <% @products.each do |product| %>
          <%= render partial: "products/card", locals: { product: product } %>
        <% end %>
        </div>
      </div>
    </div>
    <div class="map col-6">
      <div id="map"
      style="width: 100%; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>
<!-- </div> -->
<script>
  function showFilter() {
   var x = document.getElementById("show-price-filter");
   if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }       }
</script>

app/views/products/new.html.erb
<%= render "shared/new_product_form" %>

app/views/products/show.html.erb
<div class="container mt-2 ">

  <div class="back-to-products"><i class="arrow fas fa-long-arrow-alt-left"></i> <%= link_to "Back to all products", products_path %></div>

  <div class="product-info d-flex mt-4 col-4">
    <div class="product-photos mr-5">
      <div class="photos-container">
        <%= cl_image_tag @product.photos.first&.key, id: "highlight-photo" %>
      </div>
      <div class="photos">
        <% @product.photos.first(5).each do |photo| %>
        <% if @product.photos.attached? %>
          <%= cl_image_tag photo.key %>
        <% else %>
          hi
        <% end %>
        <% end %>
      </div>
    </div>

    <div class="product-description col-4">
      <p class="mb-1"><strong> Sold by </strong><%= link_to @product.user.full_name, store_path(@product.user), :target => "_blank" %></p>
      <h2 class="mb-1"><strong><%= @product.name %></strong></h2>
      <h6 class="mb-1"><%= @product.price %> € </h6>
      <% sum = 0 %>
      <% @product.reviews.each do |review|%>
      <% sum += review.stars %>
      <% sum %>
      <% end  %>

      <% if @product.reviews.count > 0  %>
      <div class="stars d-flex pt-2">
        <div class="stars-full d-flex">
          <% (sum/@product.reviews.count).times do %>
          <i class="fas fa-star"></i>
          <% end %>
        </div>

        <div class="stars-empty d-flex">
          <% (5 - (sum/@product.reviews.count)).times do %>
          <i class="far fa-star"></i>
          <% end %>
          <p class="ml-2">(<%= @product.reviews.count %>)</p>
        </div>
      </div>
      <% else %>
      <p>Seller has no reviews yet.</p>
      <% end %>



      <div class="mt-1">
        <button class="delivery-options dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Delivery Options
        </button>
        <div class="dropdown-menu delivery-dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% @product.delivery_options.each do |delivery_option| %>
          <a class="dropdown-item delivery-dropdown-item" href="#"><strong><%= delivery_option.name %>:</strong> <%= delivery_option.price %> €</a>
          <% end %>
        </div>
      </div>

      <div class="add-to-cart-button mt-2">
        <%= link_to add_to_cart_path(@product), method: :post do %>
        <button>Add to cart</button>
        <% end %>
      </div>


      <div class="wishlist-button mt-2">
        <div class="button">
          <% if @product_in_wishlist  %>
          <%= link_to delete_from_wishlist_path(@product), method: :delete do %>
          <button><i class="far fa-heart"></i> Remove from wishlist </button>
          <% end %>
          <% else %>
          <%= link_to add_to_wishlist_path(@product), method: :post do %>
          <button><i class="far fa-heart"></i> Add to wishlist </button>
          <% end %>
          <% end %>
        </div>
      </div>

 <hr class="mt-5">

      <div class="location mb-1"><i class="fas fa-map-marker-alt"></i> <%= @product.user.street_name %> <%= @product.user.street_number %>, <%= @product.user.city %></div>
      <div class="bottom-showpage d-flex">
        <div id="map"
        style="width: 480px; height: 190px;"
        data-markers="<%= @marker.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
      <div class="product-category">
        <div class="product-category-design">
          <%= @product.category.name %></div>
          <div class="product-subcategory-design">
            <%= @product.subcategory.name %></div></div>
          </div>
        </div>

<!-- <div class="delivery-options d-flex justify-content-between mb-2">
  <% @product.delivery_options.each do |delivery_option|%>
  <div class="delivery-option">
    <p><%= link_to delivery_option.name %>:<%= delivery_option.price %> </p>
  </div>
  <% end %>
</div> -->
<!-- Buttons -->

<!--   <div class="buttons">
    <%= link_to "Edit this listing", edit_product_path(@product), class: "btn btn-secondary" %>
    <button id="delete-product" class="btn btn-danger">Delete this listing</button>
    <%= link_to "", product_path(@product), method: :delete, id: "delete-link", class: "hidden" %>
  </div> -->


  <!-- Accordion start -->


  <div class="accordion mt-5 mb-5" id="accordionExample">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="accordion-button collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            + Product Descripion
          </button>
        </h5>
      </div>

      <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
        <div class="card-body-accordion">
          <p><%= @product.description %></p>
        </div>
      </div>
    </div>


    <!-- Description end -->

    <!-- Reviews start -->


    <div class="card">
      <div class="card-header" id="headingTwo">
        <h5 class="mb-0">
          <button class="accordion-button collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            + Reviews
          </button>
        </h5>
      </div>


      <!-- reviews collapse -->
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div class="card-body-accordion">

          <div class="reviews m-5">
            <div class="d-flex">
              <h3 class="mr-5">Reviews</h3>
              <div class="add-review justify-content-center align-items-center"> <%= link_to '+ Add review', new_product_review_path(@product) %></div>
            </div>
            <ul class="list-group">
              <% @product.reviews.each do |review| %>
              <div class="review mt-2 border-top">
                <div class="stars d-flex pt-2">
                  <div class="stars-full d-flex">
                    <% review.stars.times do %>
                    <i class="fas fa-star"></i>
                    <% end %>
                  </div>

                  <div class="stars-empty d-flex">
                    <% (5 - review.stars).times do %>
                    <i class="far fa-star"></i>
                    <% end %>
                  </div>
                </div>
                <div class="review-description pt-2">
                  <%= review.description%>
                  <% end %>
                </div>
              </div>
            </ul>
          </div>

          <!-- Review collapse end -->

        </div>
      </div>
    </div>
  </div>


  <!-- </div> -->